### ISSUE TITLE
Saw your post on sxhkd.

### ISSUE THREAD

**Issue by erwin** [BanchouBoo/lucky#1]
Hello.

I found lucky from your sxhkd issue post.

> It's possible to do this with [lucky](https://github.com/BanchouBoo/lucky).

I'm sure you've done a lot of work to get lucky working. I haven't downloaded and installed yet.

Would be fantastic if you could update the main /README.md to include some screenshots (maybe animated .GIF showing the related task in action)

Would also really be nice to see an example added that covers Windows Specific Keybinds.

It might also be helpful for new users if the Examples were the first thing to lead off the README.md to help orient new users to what Lucky can do for them.

Just feedback to try and help support all of your effort.

I'm looking forward to when I have time to download and experiment with lucky.

**Comment by BanchouBoo** [comment]
Done, minus the screenshots/gif, by nature an input daemon is an invisible thing, so it'd be difficult to properly convey things visually I feel.
